<a href="https://colab.research.google.com/github/Judith-solomi/AI-and-ML-Assignments/blob/main/NumPy%20%26%20Pandas%20Practice%20Task%20Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Q.1 The NumPy Array & Matrix Logic Drill
Focus: Indexing, slicing, boolean masking, and vectorized operations without loops.
"""

import numpy as np

np.random.seed(42)  # remove this line if you want different random values every run

# Task 1: Create a 5x5 matrix with random integers between 1 and 50
matrix = np.random.randint(1, 51, size=(5, 5))
print("Task 1: Original 5x5 Matrix")
print(matrix)

# Task 2: Find and print all numbers greater than 25 using boolean indexing
greater_than_25 = matrix[matrix > 25]
print("\nTask 2: Numbers greater than 25")
print(greater_than_25)

# Task 3: Replace all even numbers with 0 WITHOUT altering the original matrix
# -> work on a copy, since boolean-mask assignment mutates in place
matrix_no_even = matrix.copy()
matrix_no_even[matrix_no_even % 2 == 0] = 0
print("\nTask 3: Matrix with evens replaced by 0 (on a copy)")
print(matrix_no_even)
print("Original matrix is unchanged:")
print(matrix)

# Task 4: Normalize a 1D array of 10 elements so all values fall strictly between 0 and 1
# Formula: (x - min(x)) / (max(x) - min(x))
arr_1d = np.random.randint(1, 100, size=10).astype(float)
normalized = (arr_1d - arr_1d.min()) / (arr_1d.max() - arr_1d.min())
print("\nTask 4: Original 1D array")
print(arr_1d)
print("Normalized array (0 to 1)")
print(normalized)

Task 1: Original 5x5 Matrix
[[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]

Task 2: Numbers greater than 25
[39 29 43 39 36 40 44 30 38 33]

Task 3: Matrix with evens replaced by 0 (on a copy)
[[39 29 15 43  0]
 [21 39 19 23 11]
 [11  0  0  0  0]
 [ 3  0  0  0  0]
 [ 0  0  0 21 33]]
Original matrix is unchanged:
[[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]

Task 4: Original 1D array
[76. 58. 22. 89. 49. 91. 59. 42. 92. 60.]
Normalized array (0 to 1)
[0.77142857 0.51428571 0.         0.95714286 0.38571429 0.98571429
 0.52857143 0.28571429 1.         0.54285714]


In [2]:
"""
Q.2 The Pandas Data Cleaning & Transformation Challenge
Focus: DataFrames, handling missing values, filtering, and aggregations.
"""

import numpy as np
import pandas as pd

# Task 1: DataFrame with Employee_ID, Name, Department, Age, Salary
# (with a few intentional NaNs in Salary)
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Ravi", "Priya", "Amit", "Sneha", "Karan", "Divya"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "Age": [25, 30, 28, 35, 40, 29],
    "Salary": [50000, np.nan, 55000, np.nan, 62000, 58000]
}
df = pd.DataFrame(data)
print("Task 1: Original DataFrame")
print(df)

# Task 2: Detect and count missing values in each column
missing_counts = df.isnull().sum()
print("\nTask 2: Missing value counts per column")
print(missing_counts)

# Task 3: Fill missing Salary with the median salary of their respective Department
# groupby + transform lets each NaN get filled with ITS OWN department's median
df["Salary"] = df.groupby("Department")["Salary"].transform(
    lambda x: x.fillna(x.median())
)
print("\nTask 3: DataFrame after filling missing Salary with Department median")
print(df)

# Task 4: Annual_Bonus (10% of Salary) + average salary per department
df["Annual_Bonus"] = df["Salary"] * 0.10
avg_salary_by_dept = df.groupby("Department")["Salary"].mean()
print("\nTask 4: DataFrame with Annual_Bonus column")
print(df)
print("\nAverage Salary per Department")
print(avg_salary_by_dept)

Task 1: Original DataFrame
   Employee_ID   Name Department  Age   Salary
0          101   Ravi         IT   25  50000.0
1          102  Priya         HR   30      NaN
2          103   Amit         IT   28  55000.0
3          104  Sneha    Finance   35      NaN
4          105  Karan         HR   40  62000.0
5          106  Divya    Finance   29  58000.0

Task 2: Missing value counts per column
Employee_ID    0
Name           0
Department     0
Age            0
Salary         2
dtype: int64

Task 3: DataFrame after filling missing Salary with Department median
   Employee_ID   Name Department  Age   Salary
0          101   Ravi         IT   25  50000.0
1          102  Priya         HR   30  62000.0
2          103   Amit         IT   28  55000.0
3          104  Sneha    Finance   35  58000.0
4          105  Karan         HR   40  62000.0
5          106  Divya    Finance   29  58000.0

Task 4: DataFrame with Annual_Bonus column
   Employee_ID   Name Department  Age   Salary  Annual_Bonus


In [3]:
"""
Q.3 NumPy Array Reshaping & Slicing Challenge
Focus: Reshaping dimensions and extracting specific sub-grids.
"""

import numpy as np

# Task 1: 1D array containing numbers from 1 to 20 (inclusive)
arr_20 = np.arange(1, 21)
print("Task 1: 1D array (1 to 20)")
print(arr_20)

# Task 2: Reshape into a 4x5 matrix
matrix_4x5 = arr_20.reshape(4, 5)
print("\nTask 2: Reshaped into 4x5 matrix")
print(matrix_4x5)

# Task 3: Extract only the 2nd and 3rd columns (index 1 and 2)
cols_2_3 = matrix_4x5[:, 1:3]
print("\nTask 3: 2nd and 3rd columns")
print(cols_2_3)

# Task 4: Extract the four corner elements into a single 1D array
# Fancy indexing: pairs (0,0), (0,-1), (-1,0), (-1,-1)
rows = np.array([0, 0, -1, -1])
cols = np.array([0, -1, 0, -1])
corners = matrix_4x5[rows, cols]
print("\nTask 4: Four corner elements")
print(corners)

Task 1: 1D array (1 to 20)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Task 2: Reshaped into 4x5 matrix
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Task 3: 2nd and 3rd columns
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]

Task 4: Four corner elements
[ 1  5 16 20]


In [4]:
"""
Q.4 Pandas Filtering & Conditional Selection
Focus: Complex boolean indexing and conditional updates in DataFrames.
"""

import pandas as pd

# Task 1: DataFrame with Product, Category, Price, and Stock (at least 5 rows)
products = {
    "Product": ["Laptop", "Mouse", "Monitor", "Keyboard", "Webcam"],
    "Category": ["Electronics", "Accessories", "Electronics", "Accessories", "Electronics"],
    "Price": [55000, 450, 8500, 900, 2200],
    "Stock": [12, 150, 40, 18, 60]
}
df_products = pd.DataFrame(products)
print("Task 1: Original DataFrame")
print(df_products)

# Task 2: Filter rows where Price > 500 AND Stock < 50
filtered_products = df_products[(df_products["Price"] > 500) & (df_products["Stock"] < 50)]
print("\nTask 2: Filtered rows (Price > 500 and Stock < 50)")
print(filtered_products)

# Task 3: Add Restock_Needed column (True if Stock < 20, else False)
df_products["Restock_Needed"] = df_products["Stock"] < 20
print("\nTask 3: DataFrame with Restock_Needed column")
print(df_products)

# Task 4: Sort the final DataFrame in descending order by Price
df_sorted = df_products.sort_values(by="Price", ascending=False)
print("\nTask 4: DataFrame sorted by Price (descending)")
print(df_sorted)

Task 1: Original DataFrame
    Product     Category  Price  Stock
0    Laptop  Electronics  55000     12
1     Mouse  Accessories    450    150
2   Monitor  Electronics   8500     40
3  Keyboard  Accessories    900     18
4    Webcam  Electronics   2200     60

Task 2: Filtered rows (Price > 500 and Stock < 50)
    Product     Category  Price  Stock
0    Laptop  Electronics  55000     12
2   Monitor  Electronics   8500     40
3  Keyboard  Accessories    900     18

Task 3: DataFrame with Restock_Needed column
    Product     Category  Price  Stock  Restock_Needed
0    Laptop  Electronics  55000     12            True
1     Mouse  Accessories    450    150           False
2   Monitor  Electronics   8500     40           False
3  Keyboard  Accessories    900     18            True
4    Webcam  Electronics   2200     60           False

Task 4: DataFrame sorted by Price (descending)
    Product     Category  Price  Stock  Restock_Needed
0    Laptop  Electronics  55000     12            Tr

In [5]:
"""
Q.5 Vectorized Temperature & Math Operations
Focus: High-performance vectorization without Python for loops.
"""

import numpy as np

np.random.seed(42)  # remove this line if you want different random values every run

# Task 1: 10 random floating-point temperatures in Celsius (15.0 to 40.0)
celsius = np.random.uniform(15.0, 40.0, size=10)
print("Task 1: Celsius temperatures")
print(celsius)

# Task 2: Convert all to Fahrenheit simultaneously (vectorized)
# Formula: F = (C * 9/5) + 32
fahrenheit = (celsius * 9 / 5) + 32
print("\nTask 2: Fahrenheit temperatures")
print(fahrenheit)

# Task 3: Square root of a separate 1D array of integers 1 to 10
ints_1_to_10 = np.arange(1, 11)
sqrt_values = np.sqrt(ints_1_to_10)
print("\nTask 3: Square roots of 1-10")
print(sqrt_values)

# Task 4: Index position of the maximum temperature in the Fahrenheit array
max_index = np.argmax(fahrenheit)
print(f"\nTask 4: Index of maximum Fahrenheit temperature -> {max_index} "
      f"(value = {fahrenheit[max_index]:.2f}F)")

Task 1: Celsius temperatures
[24.36350297 38.76785766 33.29984855 29.9664621  18.90046601 18.89986301
 16.4520903  36.65440364 30.02787529 32.70181444]

Task 2: Fahrenheit temperatures
[ 75.85430535 101.78214379  91.93972738  85.93963179  66.02083882
  66.01975342  61.61376255  97.97792656  86.05017553  90.863266  ]

Task 3: Square roots of 1-10
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

Task 4: Index of maximum Fahrenheit temperature -> 1 (value = 101.78F)


In [6]:
"""
Q.6 Debugging Question 1 (NumPy Boolean Masking)
Focus: Fixing logical operator errors in vectorized environments.
"""

import numpy as np

arr = np.array([10, 25, 30, 45, 60, 15, 50])

# CORRECTED CODE
filtered_arr = arr[(arr > 20) & (arr < 50)]
print("Corrected output:")
print(filtered_arr)

Corrected output:
[25 30 45]


In [7]:
"""
Q.7 Debugging Question 2 (Pandas Column Reference)
Focus: Resolving KeyError exceptions due to mismatched column labels.
"""

import pandas as pd

data = {
    "Employee": ["Ravi", "Priya", "Amit"],
    "Department": ["IT", "HR", "Finance"],
    "Salary": [50000, 60000, 55000]
}
df = pd.DataFrame(data)
print("Available columns:", list(df.columns))

# CORRECTED CODE
df_dropped = df.drop("Salary", axis=1)
print("\nCorrected output:")
print(df_dropped)

Available columns: ['Employee', 'Department', 'Salary']

Corrected output:
  Employee Department
0     Ravi         IT
1    Priya         HR
2     Amit    Finance
